### PR TITLE
Chording

### PR DESCRIPTION
**Pull request by phedders**

### CODE REVIEW

**Comment by phedders** [comment]
Enables to use key combinations instead...

To run a command only if keys 4 and 8 are *also* held down:

`command_4_8 = "...."
`
To run commands with the scroll wheel only with key 3

`[wheel.left]
command_3 = "...."

So there is room for thousands of combinations.

Combined with my other PR. this will change to a menu of config files using the bottom button + the scroll button:

`[buttons.9]
text = ""
command_8 = "config=config-select.toml"
`

**Comment by phedders** [comment]
Pls note the dependency on #1

**Comment by phedders** [comment]
Fixed a commit ordering problem - should merge easily now.

**Comment by instance-id** [comment]
Thanks again for the contribution and additional features. This would really open up a lot more possibilities.

**Pull request merged**
